# -*- coding: utf-8 -*-
"""options.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zCVa9Fw8BrKqGJiS4YLURsGlQrAx9Y5U
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -q pyomo
# !apt-get install -y -qq glpk-utils

if options=="6:00":
  model1=pickle.load(open("./Models/1001.p", 'rb'))
  model2=pickle.load(open("./Models/2001.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

if options=="7:00":
  model1=pickle.load(open("./Models/1005.p", 'rb'))
  model2=pickle.load(open("./Models/2005.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

if options=="8:00":
  model1=pickle.load(open("./Models/1009.p", 'rb'))
  model2=pickle.load(open("./Models/2009.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

if options=="9:00":
  model1=pickle.load(open("./Models/1013.p", 'rb'))
  model2=pickle.load(open("./Models/2013.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

if options=="10:00":
  model1=pickle.load(open("./Models/1017.p", 'rb'))
  model2=pickle.load(open("./Models/2017.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

if options=="11:00":
  model1=pickle.load(open("./Models/1021.p", 'rb'))
  model2=pickle.load(open("./Models/2021.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

if options=="12:00":
  model1=pickle.load(open("./Models/1025.p", 'rb'))
  model2=pickle.load(open("./Models/2025.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

if options=="13:00":
  model1=pickle.load(open("./Models/029.p", 'rb'))
  model2=pickle.load(open("./Models/2029.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

if options=="14:00":
  model1=pickle.load(open("./Models/1033.p", 'rb'))
  model2=pickle.load(open("./Models/2033.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

if options=="15:00":
  model1=pickle.load(open("./Models/1037.p", 'rb'))
  model2=pickle.load(open("./Models/2037.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

if options=="16:00":
  model1=pickle.load(open("./Models/1041.p", 'rb'))
  model2=pickle.load(open("./Models/2041.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

if options=="17:00":
  model1=pickle.load(open("./Models/1045.p", 'rb'))
  model2=pickle.load(open("./Models/2045.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

if options=="18:00":
  model1=pickle.load(open("./Models/1049.p", 'rb'))
  model2=pickle.load(open("./Models/2049.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

if options=="19:00":
  model1=pickle.load(open("./Models/1053.p", 'rb'))
  model2=pickle.load(open("./Models/2053.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

if options=="20:00":
  model1=pickle.load(open("./Models/1057.p", 'rb'))
  model2=pickle.load(open("./Models/2057.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

if options=="21:00":
  model1=pickle.load(open("./Models/1061.p", 'rb'))
  model2=pickle.load(open("./Models/2061.p", 'rb'))
  d=[demand(model1,"A0","CK",delta), demand(model1,"A1","CK",delta), demand(model1,"A2","CK",delta), demand(model1,"A3","CK",delta), 
     demand(model1,"B0","CK",delta), demand(model1,"B1","CK",delta), demand(model1,"B2","CK",delta), demand(model1,"B3","CK",delta),
     demand(model1,"A0","CR",delta), demand(model1,"A1","CR",delta), demand(model1,"A2","CR",delta), demand(model1,"A3","CR",delta), 
     demand(model1,"B0","CR",delta), demand(model1,"B1","CR",delta), demand(model1,"B2","CR",delta), demand(model1,"B3","CR",delta),
     demand(model1,"A0","CT",delta), demand(model1,"A1","CT",delta), demand(model1,"A2","CT",delta), demand(model1,"A3","CT",delta), 
     demand(model1,"B0","CT",delta), demand(model1,"B1","CT",delta), demand(model1,"B2","CT",delta), demand(model1,"B3","CT",delta),
     demand(model1,"A0","KT",delta), demand(model1,"A1","KT",delta), demand(model1,"A2","KT",delta), demand(model1,"A3","KT",delta), 
     demand(model1,"B0","KT",delta), demand(model1,"B1","KT",delta), demand(model1,"B2","KT",delta), demand(model1,"B3","KT",delta),
     0,0,0,0,0,0,0,0,
     demand(model1,"A0","RT",delta), demand(model1,"A1","RT",delta), demand(model1,"A2","RT",delta), demand(model1,"A3","RT",delta), 
     demand(model1,"B0","RT",delta), demand(model1,"B1","RT",delta), demand(model1,"B2","RT",delta), demand(model1,"B3","RT",delta),
     demand(model2,"A0","KC",delta), demand(model2,"A1","KC",delta), demand(model2,"A2","KC",delta), demand(model2,"A3","KC",delta), 
     demand(model2,"B0","KC",delta), demand(model2,"B1","KC",delta), demand(model2,"B2","KC",delta), demand(model2,"B3","KC",delta),
     demand(model2,"A0","RC",delta), demand(model2,"A1","RC",delta), demand(model2,"A2","RC",delta), demand(model2,"A3","RC",delta), 
     demand(model2,"B0","RC",delta), demand(model2,"B1","RC",delta), demand(model2,"B2","RC",delta), demand(model2,"B3","RC",delta),
     demand(model2,"A0","TC",delta), demand(model2,"A1","TC",delta), demand(model2,"A2","TC",delta), demand(model2,"A3","TC",delta), 
     demand(model2,"B0","TC",delta), demand(model2,"B1","TC",delta), demand(model2,"B2","TC",delta), demand(model2,"B3","TC",delta),
     demand(model2,"A0","TK",delta), demand(model2,"A1","TK",delta), demand(model2,"A2","TK",delta), demand(model2,"A3","TK",delta), 
     demand(model2,"B0","TK",delta), demand(model2,"B1","TK",delta), demand(model2,"B2","TK",delta), demand(model2,"B3","TK",delta),
     0,0,0,0,0,0,0,0,
     demand(model2,"A0","TR",delta), demand(model2,"A1","TR",delta), demand(model2,"A2","TR",delta), demand(model2,"A3","TR",delta), 
     demand(model2,"B0","TR",delta), demand(model2,"B1","TR",delta), demand(model2,"B2","TR",delta), demand(model2,"B3","TR",delta),
     ]

